# Generated by Django 4.2.17 on 2024-12-27 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_timings_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
